sections:
  main:
    display: Main
    fields:
      -
        handle: name
        field:
          input_type: text
          display: Name
          type: text
          icon: text
          listable: hidden
      -
        handle: short_locale
        field:
          input_type: text
          antlers: false
          display: 'Short Locale'
          type: text
          icon: text
          listable: hidden
